permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - '.github/workflows/release.yml'
  push:
    branches:
      - 'master'
      - 'v1.16'
      - 'v1.17'
      - 'v1.18'
      - 'v2.0'
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ["${{ matrix.os }}"]

    steps:
      - uses: actions/checkout@v4

      - name: Set rust version
        run: |
          RUST_VERSION="$(grep -oP 'channel = "\K\d\.\d+\.\d+(?=")' rust-toolchain.toml)"
          echo "RUST_STABLE_VERSION=$RUST_VERSION" >> "$GITHUB_ENV"

      - name: Set env vars
        run: |
          source ci/env.sh
          echo "GEYSER_PLUGIN_NAME=$plugin_name" | tee -a $GITHUB_ENV
          echo "GEYSER_PLUGIN_LIB=lib${plugin_lib_name}" | tee -a $GITHUB_ENV

      - if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev libssl-dev libsasl2-dev libzstd-dev

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target
          key: cargo-${{ matrix.os }}-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('**/Cargo.lock') }}-0000
          restore-keys: |
            cargo-${{ matrix.os }}-${{ hashFiles('rust-toolchain.toml') }}

      - name: Check Solana version
        run: |
          echo "CI_TAG=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"
          echo "CI_OS_NAME=linux" >> "$GITHUB_ENV"

          SOLANA_VERSION="$(./ci/solana-version.sh)"
          SOLANA_VERSION="v${SOLANA_VERSION#=}"
          echo "SOLANA_VERSION=$SOLANA_VERSION" >> "$GITHUB_ENV"

      - name: Create build name
        run: |
          echo "BUILD_NAME=$CI_TAG" >> "$GITHUB_ENV"

      - name: Build release tarball
        run: ./ci/create-tarball.sh

      - name: Rename binaries for ubuntu22 release
        if: matrix.os == 'ubuntu-22.04'
        run: |
          mv target/release/config target/release/config-22
          mv target/release/consumer target/release/consumer-22
          mv ${{ env.GEYSER_PLUGIN_NAME }}-release-x86_64-unknown-linux-gnu.tar.bz2 ${{ env.GEYSER_PLUGIN_NAME }}-release22-x86_64-unknown-linux-gnu.tar.bz2
          mv ${{ env.GEYSER_PLUGIN_NAME }}-release-x86_64-unknown-linux-gnu.yml ${{ env.GEYSER_PLUGIN_NAME }}-release22-x86_64-unknown-linux-gnu.yml

      - name: Deleteing .d files
        run: |
          rm -rf target/release/config.d target/release/consumer.d

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.BUILD_NAME }}
          body: |
            ${{ env.GEYSER_PLUGIN_NAME }} ${{ env.CI_TAG }}
            solana ${{ env.SOLANA_VERSION }}
            rust ${{ env.RUST_VERSION }}
          files: |
            ${{ env.GEYSER_PLUGIN_NAME }}-release*
            target/release/config*
            target/release/consumer*
